# Development Environment Configuration
environment: development
debug: true

database:
  host: localhost
  port: 5432
  database: ors
  username: postgres
  password: postgres
  schema: retail_dw
  pool_size: 10
  max_overflow: 20

etl:
  batch_size: 500
  max_retries: 3
  retry_delay: 5
  enable_monitoring: true
  data_quality_threshold: 0.9

monitoring:
  enable_prometheus: true
  prometheus_port: 8000
  log_level: DEBUG
  alert_email: null

cache:
  redis_host: localhost
  redis_port: 6379
  redis_db: 0
  cache_ttl: 1800